/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public class CloseOpenMouthDetector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CloseOpenMouthDetector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CloseOpenMouthDetector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GestureEstimateJNI.delete_CloseOpenMouthDetector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CloseOpenMouthDetector() {
    this(GestureEstimateJNI.new_CloseOpenMouthDetector(), true);
  }

  public boolean IsMouthOpen(Point3fList face) {
    return GestureEstimateJNI.CloseOpenMouthDetector_IsMouthOpen(swigCPtr, this, Point3fList.getCPtr(face), face);
  }

  public void SetMouthOpenThres(float mouth_aspect_ratio) {
    GestureEstimateJNI.CloseOpenMouthDetector_SetMouthOpenThres(swigCPtr, this, mouth_aspect_ratio);
  }

}
