/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public class CloseOpenEyeDetector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CloseOpenEyeDetector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CloseOpenEyeDetector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GestureEstimateJNI.delete_CloseOpenEyeDetector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CloseOpenEyeDetector() {
    this(GestureEstimateJNI.new_CloseOpenEyeDetector(), true);
  }

  public EyeStatusEnum GetEyeStatus(Point3fList face) {
    return EyeStatusEnum.swigToEnum(GestureEstimateJNI.CloseOpenEyeDetector_GetEyeStatus(swigCPtr, this, Point3fList.getCPtr(face), face));
  }

  public void SetEyeOpenThres(float eye_aspect_ratio) {
    GestureEstimateJNI.CloseOpenEyeDetector_SetEyeOpenThres(swigCPtr, this, eye_aspect_ratio);
  }

}
