/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public class DragDetector extends Detector {
  private transient long swigCPtr;

  protected DragDetector(long cPtr, boolean cMemoryOwn) {
    super(GestureEstimateJNI.DragDetector_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DragDetector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GestureEstimateJNI.delete_DragDetector(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public boolean OnDragLeft(Point3fList left) {
    return GestureEstimateJNI.DragDetector_OnDragLeft(swigCPtr, this, Point3fList.getCPtr(left), left);
  }

  public boolean OnDragRight(Point3fList right) {
    return GestureEstimateJNI.DragDetector_OnDragRight(swigCPtr, this, Point3fList.getCPtr(right), right);
  }

  public DragDetector() {
    this(GestureEstimateJNI.new_DragDetector(), true);
  }

}
