/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public class FaceEulerAngle {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FaceEulerAngle(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FaceEulerAngle obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GestureEstimateJNI.delete_FaceEulerAngle(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPitch(float value) {
    GestureEstimateJNI.FaceEulerAngle_pitch_set(swigCPtr, this, value);
  }

  public float getPitch() {
    return GestureEstimateJNI.FaceEulerAngle_pitch_get(swigCPtr, this);
  }

  public void setYaw(float value) {
    GestureEstimateJNI.FaceEulerAngle_yaw_set(swigCPtr, this, value);
  }

  public float getYaw() {
    return GestureEstimateJNI.FaceEulerAngle_yaw_get(swigCPtr, this);
  }

  public void setRoll(float value) {
    GestureEstimateJNI.FaceEulerAngle_roll_set(swigCPtr, this, value);
  }

  public float getRoll() {
    return GestureEstimateJNI.FaceEulerAngle_roll_get(swigCPtr, this);
  }

  public FaceEulerAngle() {
    this(GestureEstimateJNI.new_FaceEulerAngle(), true);
  }

}
