/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public class HandList extends java.util.AbstractList<Hand> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected HandList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(HandList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GestureEstimateJNI.delete_HandList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public HandList(Hand[] initialElements) {
    this();
    reserve(initialElements.length);

    for (Hand element : initialElements) {
      add(element);
    }
  }

  public HandList(Iterable<Hand> initialElements) {
    this();
    for (Hand element : initialElements) {
      add(element);
    }
  }

  public Hand get(int index) {
    return doGet(index);
  }

  public Hand set(int index, Hand e) {
    return doSet(index, e);
  }

  public boolean add(Hand e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Hand e) {
    modCount++;
    doAdd(index, e);
  }

  public Hand remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public HandList() {
    this(GestureEstimateJNI.new_HandList__SWIG_0(), true);
  }

  public HandList(HandList other) {
    this(GestureEstimateJNI.new_HandList__SWIG_1(HandList.getCPtr(other), other), true);
  }

  public long capacity() {
    return GestureEstimateJNI.HandList_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    GestureEstimateJNI.HandList_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return GestureEstimateJNI.HandList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    GestureEstimateJNI.HandList_clear(swigCPtr, this);
  }

  public HandList(int count, Hand value) {
    this(GestureEstimateJNI.new_HandList__SWIG_2(count, value.swigValue()), true);
  }

  private int doSize() {
    return GestureEstimateJNI.HandList_doSize(swigCPtr, this);
  }

  private void doAdd(Hand x) {
    GestureEstimateJNI.HandList_doAdd__SWIG_0(swigCPtr, this, x.swigValue());
  }

  private void doAdd(int index, Hand x) {
    GestureEstimateJNI.HandList_doAdd__SWIG_1(swigCPtr, this, index, x.swigValue());
  }

  private Hand doRemove(int index) {
    return Hand.swigToEnum(GestureEstimateJNI.HandList_doRemove(swigCPtr, this, index));
  }

  private Hand doGet(int index) {
    return Hand.swigToEnum(GestureEstimateJNI.HandList_doGet(swigCPtr, this, index));
  }

  private Hand doSet(int index, Hand val) {
    return Hand.swigToEnum(GestureEstimateJNI.HandList_doSet(swigCPtr, this, index, val.swigValue()));
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    GestureEstimateJNI.HandList_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
