/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public final class HandPoseEnum {
  public final static HandPoseEnum Fist = new HandPoseEnum("Fist");
  public final static HandPoseEnum One = new HandPoseEnum("One");
  public final static HandPoseEnum Two = new HandPoseEnum("Two");
  public final static HandPoseEnum Three = new HandPoseEnum("Three");
  public final static HandPoseEnum Four = new HandPoseEnum("Four");
  public final static HandPoseEnum Five = new HandPoseEnum("Five");
  public final static HandPoseEnum Six = new HandPoseEnum("Six");
  public final static HandPoseEnum Seven = new HandPoseEnum("Seven");
  public final static HandPoseEnum Eight = new HandPoseEnum("Eight");
  public final static HandPoseEnum Nine = new HandPoseEnum("Nine");
  public final static HandPoseEnum Love = new HandPoseEnum("Love");
  public final static HandPoseEnum ThumbUp = new HandPoseEnum("ThumbUp");
  public final static HandPoseEnum HeartSingle = new HandPoseEnum("HeartSingle");
  public final static HandPoseEnum OK = new HandPoseEnum("OK");
  public final static HandPoseEnum Rock = new HandPoseEnum("Rock");
  public final static HandPoseEnum Insult = new HandPoseEnum("Insult");
  public final static HandPoseEnum ThumbDown = new HandPoseEnum("ThumbDown");
  public final static HandPoseEnum Unkonwn = new HandPoseEnum("Unkonwn");
  public final static HandPoseEnum Worst = new HandPoseEnum("Worst");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static HandPoseEnum swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + HandPoseEnum.class + " with value " + swigValue);
  }

  private HandPoseEnum(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private HandPoseEnum(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private HandPoseEnum(String swigName, HandPoseEnum swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static HandPoseEnum[] swigValues = { Fist, One, Two, Three, Four, Five, Six, Seven, Eight, Nine, Love, ThumbUp, HeartSingle, OK, Rock, Insult, ThumbDown, Unkonwn, Worst };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

