/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public class OptionalPoint2f {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OptionalPoint2f(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OptionalPoint2f obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GestureEstimateJNI.delete_OptionalPoint2f(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public OptionalPoint2f() {
    this(GestureEstimateJNI.new_OptionalPoint2f__SWIG_0(), true);
  }

  public OptionalPoint2f(Point2f value) {
    this(GestureEstimateJNI.new_OptionalPoint2f__SWIG_1(Point2f.getCPtr(value), value), true);
  }

  public OptionalPoint2f(OptionalPoint2f other) {
    this(GestureEstimateJNI.new_OptionalPoint2f__SWIG_2(OptionalPoint2f.getCPtr(other), other), true);
  }

  public OptionalPoint2f assign(Point2f value) {
    return new OptionalPoint2f(GestureEstimateJNI.OptionalPoint2f_assign__SWIG_0(swigCPtr, this, Point2f.getCPtr(value), value), false);
  }

  public OptionalPoint2f assign(OptionalPoint2f other) {
    return new OptionalPoint2f(GestureEstimateJNI.OptionalPoint2f_assign__SWIG_1(swigCPtr, this, OptionalPoint2f.getCPtr(other), other), false);
  }

  public void swap(OptionalPoint2f other) {
    GestureEstimateJNI.OptionalPoint2f_swap(swigCPtr, this, OptionalPoint2f.getCPtr(other), other);
  }

  public Point2f value() {
    return new Point2f(GestureEstimateJNI.OptionalPoint2f_value(swigCPtr, this), false);
  }

  public Point2f value_or(Point2f deflt) {
    return new Point2f(GestureEstimateJNI.OptionalPoint2f_value_or(swigCPtr, this, Point2f.getCPtr(deflt), deflt), false);
  }

  public boolean is_specified() {
    return GestureEstimateJNI.OptionalPoint2f_is_specified(swigCPtr, this);
  }

  public void clear() {
    GestureEstimateJNI.OptionalPoint2f_clear(swigCPtr, this);
  }

}
