/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public class Point2iList extends java.util.AbstractList<Point2i> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Point2iList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Point2iList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GestureEstimateJNI.delete_Point2iList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Point2iList(Point2i[] initialElements) {
    this();
    reserve(initialElements.length);

    for (Point2i element : initialElements) {
      add(element);
    }
  }

  public Point2iList(Iterable<Point2i> initialElements) {
    this();
    for (Point2i element : initialElements) {
      add(element);
    }
  }

  public Point2i get(int index) {
    return doGet(index);
  }

  public Point2i set(int index, Point2i e) {
    return doSet(index, e);
  }

  public boolean add(Point2i e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Point2i e) {
    modCount++;
    doAdd(index, e);
  }

  public Point2i remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public Point2iList() {
    this(GestureEstimateJNI.new_Point2iList__SWIG_0(), true);
  }

  public Point2iList(Point2iList other) {
    this(GestureEstimateJNI.new_Point2iList__SWIG_1(Point2iList.getCPtr(other), other), true);
  }

  public long capacity() {
    return GestureEstimateJNI.Point2iList_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    GestureEstimateJNI.Point2iList_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return GestureEstimateJNI.Point2iList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    GestureEstimateJNI.Point2iList_clear(swigCPtr, this);
  }

  public Point2iList(int count, Point2i value) {
    this(GestureEstimateJNI.new_Point2iList__SWIG_2(count, Point2i.getCPtr(value), value), true);
  }

  private int doSize() {
    return GestureEstimateJNI.Point2iList_doSize(swigCPtr, this);
  }

  private void doAdd(Point2i x) {
    GestureEstimateJNI.Point2iList_doAdd__SWIG_0(swigCPtr, this, Point2i.getCPtr(x), x);
  }

  private void doAdd(int index, Point2i x) {
    GestureEstimateJNI.Point2iList_doAdd__SWIG_1(swigCPtr, this, index, Point2i.getCPtr(x), x);
  }

  private Point2i doRemove(int index) {
    return new Point2i(GestureEstimateJNI.Point2iList_doRemove(swigCPtr, this, index), true);
  }

  private Point2i doGet(int index) {
    return new Point2i(GestureEstimateJNI.Point2iList_doGet(swigCPtr, this, index), false);
  }

  private Point2i doSet(int index, Point2i val) {
    return new Point2i(GestureEstimateJNI.Point2iList_doSet(swigCPtr, this, index, Point2i.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    GestureEstimateJNI.Point2iList_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
