/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public class Point2dList extends java.util.AbstractList<Point2d> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Point2dList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Point2dList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GestureEstimateJNI.delete_Point2dList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Point2dList(Point2d[] initialElements) {
    this();
    reserve(initialElements.length);

    for (Point2d element : initialElements) {
      add(element);
    }
  }

  public Point2dList(Iterable<Point2d> initialElements) {
    this();
    for (Point2d element : initialElements) {
      add(element);
    }
  }

  public Point2d get(int index) {
    return doGet(index);
  }

  public Point2d set(int index, Point2d e) {
    return doSet(index, e);
  }

  public boolean add(Point2d e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Point2d e) {
    modCount++;
    doAdd(index, e);
  }

  public Point2d remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public Point2dList() {
    this(GestureEstimateJNI.new_Point2dList__SWIG_0(), true);
  }

  public Point2dList(Point2dList other) {
    this(GestureEstimateJNI.new_Point2dList__SWIG_1(Point2dList.getCPtr(other), other), true);
  }

  public long capacity() {
    return GestureEstimateJNI.Point2dList_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    GestureEstimateJNI.Point2dList_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return GestureEstimateJNI.Point2dList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    GestureEstimateJNI.Point2dList_clear(swigCPtr, this);
  }

  public Point2dList(int count, Point2d value) {
    this(GestureEstimateJNI.new_Point2dList__SWIG_2(count, Point2d.getCPtr(value), value), true);
  }

  private int doSize() {
    return GestureEstimateJNI.Point2dList_doSize(swigCPtr, this);
  }

  private void doAdd(Point2d x) {
    GestureEstimateJNI.Point2dList_doAdd__SWIG_0(swigCPtr, this, Point2d.getCPtr(x), x);
  }

  private void doAdd(int index, Point2d x) {
    GestureEstimateJNI.Point2dList_doAdd__SWIG_1(swigCPtr, this, index, Point2d.getCPtr(x), x);
  }

  private Point2d doRemove(int index) {
    return new Point2d(GestureEstimateJNI.Point2dList_doRemove(swigCPtr, this, index), true);
  }

  private Point2d doGet(int index) {
    return new Point2d(GestureEstimateJNI.Point2dList_doGet(swigCPtr, this, index), false);
  }

  private Point2d doSet(int index, Point2d val) {
    return new Point2d(GestureEstimateJNI.Point2dList_doSet(swigCPtr, this, index, Point2d.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    GestureEstimateJNI.Point2dList_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
