/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public class Point3fList extends java.util.AbstractList<Point3f> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Point3fList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Point3fList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GestureEstimateJNI.delete_Point3fList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Point3fList(Point3f[] initialElements) {
    this();
    reserve(initialElements.length);

    for (Point3f element : initialElements) {
      add(element);
    }
  }

  public Point3fList(Iterable<Point3f> initialElements) {
    this();
    for (Point3f element : initialElements) {
      add(element);
    }
  }

  public Point3f get(int index) {
    return doGet(index);
  }

  public Point3f set(int index, Point3f e) {
    return doSet(index, e);
  }

  public boolean add(Point3f e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Point3f e) {
    modCount++;
    doAdd(index, e);
  }

  public Point3f remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public Point3fList() {
    this(GestureEstimateJNI.new_Point3fList__SWIG_0(), true);
  }

  public Point3fList(Point3fList other) {
    this(GestureEstimateJNI.new_Point3fList__SWIG_1(Point3fList.getCPtr(other), other), true);
  }

  public long capacity() {
    return GestureEstimateJNI.Point3fList_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    GestureEstimateJNI.Point3fList_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return GestureEstimateJNI.Point3fList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    GestureEstimateJNI.Point3fList_clear(swigCPtr, this);
  }

  public Point3fList(int count, Point3f value) {
    this(GestureEstimateJNI.new_Point3fList__SWIG_2(count, Point3f.getCPtr(value), value), true);
  }

  private int doSize() {
    return GestureEstimateJNI.Point3fList_doSize(swigCPtr, this);
  }

  private void doAdd(Point3f x) {
    GestureEstimateJNI.Point3fList_doAdd__SWIG_0(swigCPtr, this, Point3f.getCPtr(x), x);
  }

  private void doAdd(int index, Point3f x) {
    GestureEstimateJNI.Point3fList_doAdd__SWIG_1(swigCPtr, this, index, Point3f.getCPtr(x), x);
  }

  private Point3f doRemove(int index) {
    return new Point3f(GestureEstimateJNI.Point3fList_doRemove(swigCPtr, this, index), true);
  }

  private Point3f doGet(int index) {
    return new Point3f(GestureEstimateJNI.Point3fList_doGet(swigCPtr, this, index), false);
  }

  private Point3f doSet(int index, Point3f val) {
    return new Point3f(GestureEstimateJNI.Point3fList_doSet(swigCPtr, this, index, Point3f.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    GestureEstimateJNI.Point3fList_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
