/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public class Point3d {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Point3d(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Point3d obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GestureEstimateJNI.delete_Point3d(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Point3d() {
    this(GestureEstimateJNI.new_Point3d__SWIG_0(), true);
  }

  public Point3d(double _x, double _y, double _z) {
    this(GestureEstimateJNI.new_Point3d__SWIG_1(_x, _y, _z), true);
  }

  public double dot(Point3d pt) {
    return GestureEstimateJNI.Point3d_dot(swigCPtr, this, Point3d.getCPtr(pt), pt);
  }

  public double ddot(Point3d pt) {
    return GestureEstimateJNI.Point3d_ddot(swigCPtr, this, Point3d.getCPtr(pt), pt);
  }

  public Point3d cross(Point3d pt) {
    return new Point3d(GestureEstimateJNI.Point3d_cross(swigCPtr, this, Point3d.getCPtr(pt), pt), true);
  }

  public void setX(double value) {
    GestureEstimateJNI.Point3d_x_set(swigCPtr, this, value);
  }

  public double getX() {
    return GestureEstimateJNI.Point3d_x_get(swigCPtr, this);
  }

  public void setY(double value) {
    GestureEstimateJNI.Point3d_y_set(swigCPtr, this, value);
  }

  public double getY() {
    return GestureEstimateJNI.Point3d_y_get(swigCPtr, this);
  }

  public void setZ(double value) {
    GestureEstimateJNI.Point3d_z_set(swigCPtr, this, value);
  }

  public double getZ() {
    return GestureEstimateJNI.Point3d_z_get(swigCPtr, this);
  }

}
