/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public class RunWalkAndStandV2Detector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RunWalkAndStandV2Detector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RunWalkAndStandV2Detector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GestureEstimateJNI.delete_RunWalkAndStandV2Detector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RunWalkAndStandV2Detector() {
    this(GestureEstimateJNI.new_RunWalkAndStandV2Detector(), true);
  }

  public void SetRunWalkAndStandV2TimeParam(int frame_len, float run_delay_time, float walk_delay_time) {
    GestureEstimateJNI.RunWalkAndStandV2Detector_SetRunWalkAndStandV2TimeParam(swigCPtr, this, frame_len, run_delay_time, walk_delay_time);
  }

  public void SetRunWalkAndStandV2MoveParam(float ankle_height_move_thres, float run_wrist_height_thres, float turn_round_recognation_angle) {
    GestureEstimateJNI.RunWalkAndStandV2Detector_SetRunWalkAndStandV2MoveParam(swigCPtr, this, ankle_height_move_thres, run_wrist_height_thres, turn_round_recognation_angle);
  }

  public ActionPoseV2Enum On(Point3fList body, Point3fList body3d2d) {
    return ActionPoseV2Enum.swigToEnum(GestureEstimateJNI.RunWalkAndStandV2Detector_On(swigCPtr, this, Point3fList.getCPtr(body), body, Point3fList.getCPtr(body3d2d), body3d2d));
  }

}
