/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public class SlipDetector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SlipDetector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SlipDetector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GestureEstimateJNI.delete_SlipDetector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SlipDetector() {
    this(GestureEstimateJNI.new_SlipDetector(), true);
  }

  public SlipEnum OnSlip(Point3fList body) {
    return SlipEnum.swigToEnum(GestureEstimateJNI.SlipDetector_OnSlip(swigCPtr, this, Point3fList.getCPtr(body), body));
  }

}
