/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public class StaticHandPoseDetector extends Detector {
  private transient long swigCPtr;

  protected StaticHandPoseDetector(long cPtr, boolean cMemoryOwn) {
    super(GestureEstimateJNI.StaticHandPoseDetector_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StaticHandPoseDetector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GestureEstimateJNI.delete_StaticHandPoseDetector(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static HandPoseEnum Detect(Point3fList hand_kpt) {
    return HandPoseEnum.swigToEnum(GestureEstimateJNI.StaticHandPoseDetector_Detect(Point3fList.getCPtr(hand_kpt), hand_kpt));
  }

  public StaticHandPoseDetector() {
    this(GestureEstimateJNI.new_StaticHandPoseDetector(), true);
  }

}
