/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public class TwoFingerSlidingDetector extends Detector {
  private transient long swigCPtr;

  protected TwoFingerSlidingDetector(long cPtr, boolean cMemoryOwn) {
    super(GestureEstimateJNI.TwoFingerSlidingDetector_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TwoFingerSlidingDetector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GestureEstimateJNI.delete_TwoFingerSlidingDetector(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public OptionalVec2f On(Point3fList hand) {
    return new OptionalVec2f(GestureEstimateJNI.TwoFingerSlidingDetector_On(swigCPtr, this, Point3fList.getCPtr(hand), hand), true);
  }

  public OptionalVec2f OnLeftSliding(Point3fList left) {
    return new OptionalVec2f(GestureEstimateJNI.TwoFingerSlidingDetector_OnLeftSliding(swigCPtr, this, Point3fList.getCPtr(left), left), true);
  }

  public OptionalVec2f OnRightSliding(Point3fList right) {
    return new OptionalVec2f(GestureEstimateJNI.TwoFingerSlidingDetector_OnRightSliding(swigCPtr, this, Point3fList.getCPtr(right), right), true);
  }

  public TwoFingerSlidingDetector() {
    this(GestureEstimateJNI.new_TwoFingerSlidingDetector(), true);
  }

}
