/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public class WaveHandDetector extends Detector {
  private transient long swigCPtr;

  protected WaveHandDetector(long cPtr, boolean cMemoryOwn) {
    super(GestureEstimateJNI.WaveHandDetector_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(WaveHandDetector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GestureEstimateJNI.delete_WaveHandDetector(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public boolean OnWaveLeftHand(Point3fList left) {
    return GestureEstimateJNI.WaveHandDetector_OnWaveLeftHand(swigCPtr, this, Point3fList.getCPtr(left), left);
  }

  public boolean OnWaveRightHand(Point3fList right) {
    return GestureEstimateJNI.WaveHandDetector_OnWaveRightHand(swigCPtr, this, Point3fList.getCPtr(right), right);
  }

  public WaveHandDetector() {
    this(GestureEstimateJNI.new_WaveHandDetector(), true);
  }

}
