/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public class ZwnHorizontalWaveConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ZwnHorizontalWaveConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ZwnHorizontalWaveConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GestureEstimateJNI.delete_ZwnHorizontalWaveConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMove_horizontal_thres(float value) {
    GestureEstimateJNI.ZwnHorizontalWaveConfig_move_horizontal_thres_set(swigCPtr, this, value);
  }

  public float getMove_horizontal_thres() {
    return GestureEstimateJNI.ZwnHorizontalWaveConfig_move_horizontal_thres_get(swigCPtr, this);
  }

  public void setMove_vertical_slope_thres(float value) {
    GestureEstimateJNI.ZwnHorizontalWaveConfig_move_vertical_slope_thres_set(swigCPtr, this, value);
  }

  public float getMove_vertical_slope_thres() {
    return GestureEstimateJNI.ZwnHorizontalWaveConfig_move_vertical_slope_thres_get(swigCPtr, this);
  }

  public void setMove_pass_inside_wrist_shoulder_thres(float value) {
    GestureEstimateJNI.ZwnHorizontalWaveConfig_move_pass_inside_wrist_shoulder_thres_set(swigCPtr, this, value);
  }

  public float getMove_pass_inside_wrist_shoulder_thres() {
    return GestureEstimateJNI.ZwnHorizontalWaveConfig_move_pass_inside_wrist_shoulder_thres_get(swigCPtr, this);
  }

  public void setMove_pass_outside_wrist_shoulder_thres(float value) {
    GestureEstimateJNI.ZwnHorizontalWaveConfig_move_pass_outside_wrist_shoulder_thres_set(swigCPtr, this, value);
  }

  public float getMove_pass_outside_wrist_shoulder_thres() {
    return GestureEstimateJNI.ZwnHorizontalWaveConfig_move_pass_outside_wrist_shoulder_thres_get(swigCPtr, this);
  }

  public ZwnHorizontalWaveConfig() {
    this(GestureEstimateJNI.new_ZwnHorizontalWaveConfig(), true);
  }

}
