/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public class ArmCrossDetector extends Detector {
  private transient long swigCPtr;

  protected ArmCrossDetector(long cPtr, boolean cMemoryOwn) {
    super(GestureEstimateJNI.ArmCrossDetector_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ArmCrossDetector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GestureEstimateJNI.delete_ArmCrossDetector(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public OptionalPoint2f On(Point3fList body) {
    return new OptionalPoint2f(GestureEstimateJNI.ArmCrossDetector_On(swigCPtr, this, Point3fList.getCPtr(body), body), true);
  }

  public void SetExpandWristThres(float expand_wrist_thres, float arm_shoulder_max_angle, float two_arm_max_angle) {
    GestureEstimateJNI.ArmCrossDetector_SetExpandWristThres(swigCPtr, this, expand_wrist_thres, arm_shoulder_max_angle, two_arm_max_angle);
  }

  public FloatList GetExpandWristThres() {
    return new FloatList(GestureEstimateJNI.ArmCrossDetector_GetExpandWristThres(swigCPtr, this), true);
  }

  public ArmCrossDetector() {
    this(GestureEstimateJNI.new_ArmCrossDetector(), true);
  }

}
