/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public class ArmsRaisedToRight {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ArmsRaisedToRight(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ArmsRaisedToRight obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GestureEstimateJNI.delete_ArmsRaisedToRight(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean Detect(Point3fList body) {
    return GestureEstimateJNI.ArmsRaisedToRight_Detect(swigCPtr, this, Point3fList.getCPtr(body), body);
  }

  public void setShoulder_straight_angle(float value) {
    GestureEstimateJNI.ArmsRaisedToRight_shoulder_straight_angle_set(swigCPtr, this, value);
  }

  public float getShoulder_straight_angle() {
    return GestureEstimateJNI.ArmsRaisedToRight_shoulder_straight_angle_get(swigCPtr, this);
  }

  public void setElbow_straight_angle(float value) {
    GestureEstimateJNI.ArmsRaisedToRight_elbow_straight_angle_set(swigCPtr, this, value);
  }

  public float getElbow_straight_angle() {
    return GestureEstimateJNI.ArmsRaisedToRight_elbow_straight_angle_get(swigCPtr, this);
  }

  public ArmsRaisedToRight() {
    this(GestureEstimateJNI.new_ArmsRaisedToRight(), true);
  }

}
