/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public class Cutdownward {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Cutdownward(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Cutdownward obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GestureEstimateJNI.delete_Cutdownward(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Cutdownward() {
    this(GestureEstimateJNI.new_Cutdownward(), true);
  }

  public boolean DetectCutdownward(Point3f wrist, Point3f elbow, Point3f shoulder) {
    return GestureEstimateJNI.Cutdownward_DetectCutdownward(swigCPtr, this, Point3f.getCPtr(wrist), wrist, Point3f.getCPtr(elbow), elbow, Point3f.getCPtr(shoulder), shoulder);
  }

}
