/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public class Detector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Detector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Detector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GestureEstimateJNI.delete_Detector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Detector() {
    this(GestureEstimateJNI.new_Detector__SWIG_0(), true);
  }

  public Detector(MotionCallback callback) {
    this(GestureEstimateJNI.new_Detector__SWIG_1(MotionCallback.getCPtr(callback), callback), true);
  }

  public boolean Detect(LandmarkSet kpts) {
    return GestureEstimateJNI.Detector_Detect(swigCPtr, this, LandmarkSet.getCPtr(kpts), kpts);
  }

  public void set_frame_len(int frame_len) {
    GestureEstimateJNI.Detector_set_frame_len(swigCPtr, this, frame_len);
  }

  public void set_jump_shoulder_scale(float jump_shoulder_scale, float foot_chg) {
    GestureEstimateJNI.Detector_set_jump_shoulder_scale(swigCPtr, this, jump_shoulder_scale, foot_chg);
  }

  public void set_callback(MotionCallback callback) {
    GestureEstimateJNI.Detector_set_callback(swigCPtr, this, MotionCallback.getCPtr(callback), callback);
  }

}
