/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public class HandsUpV2Detector extends Detector {
  private transient long swigCPtr;

  protected HandsUpV2Detector(long cPtr, boolean cMemoryOwn) {
    super(GestureEstimateJNI.HandsUpV2Detector_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(HandsUpV2Detector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GestureEstimateJNI.delete_HandsUpV2Detector(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public boolean OnLeftHandUpV2(Point3fList body) {
    return GestureEstimateJNI.HandsUpV2Detector_OnLeftHandUpV2(swigCPtr, this, Point3fList.getCPtr(body), body);
  }

  public boolean OnRightHandUpV2(Point3fList body) {
    return GestureEstimateJNI.HandsUpV2Detector_OnRightHandUpV2(swigCPtr, this, Point3fList.getCPtr(body), body);
  }

  public boolean OnBothHandUpV2(Point3fList body) {
    return GestureEstimateJNI.HandsUpV2Detector_OnBothHandUpV2(swigCPtr, this, Point3fList.getCPtr(body), body);
  }

  public void SetLeftHandUpV2Thres(float right_up_arm_right_body_max_angle, float left_small_arm_left_body_min_angle) {
    GestureEstimateJNI.HandsUpV2Detector_SetLeftHandUpV2Thres(swigCPtr, this, right_up_arm_right_body_max_angle, left_small_arm_left_body_min_angle);
  }

  public void SetRightHandUpV2Thres(float left_up_arm_left_body_max_angle, float right_small_arm_right_body_min_angle) {
    GestureEstimateJNI.HandsUpV2Detector_SetRightHandUpV2Thres(swigCPtr, this, left_up_arm_left_body_max_angle, right_small_arm_right_body_min_angle);
  }

  public void SetBothHandUpV2Thres(float right_wirst_shoulder_hip_min_angle, float left_wirst_shoulder_hip_min_angle) {
    GestureEstimateJNI.HandsUpV2Detector_SetBothHandUpV2Thres(swigCPtr, this, right_wirst_shoulder_hip_min_angle, left_wirst_shoulder_hip_min_angle);
  }

  public HandsUpV2Detector() {
    this(GestureEstimateJNI.new_HandsUpV2Detector(), true);
  }

}
