/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public final class Hand {
  public final static Hand LeftHand = new Hand("LeftHand");
  public final static Hand RightHand = new Hand("RightHand");
  public final static Hand Unkonwn = new Hand("Unkonwn");
  public final static Hand BothHand = new Hand("BothHand");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Hand swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Hand.class + " with value " + swigValue);
  }

  private Hand(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Hand(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Hand(String swigName, Hand swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Hand[] swigValues = { LeftHand, RightHand, Unkonwn, BothHand };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

