/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public class Point3dList extends java.util.AbstractList<Point3d> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Point3dList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Point3dList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GestureEstimateJNI.delete_Point3dList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Point3dList(Point3d[] initialElements) {
    this();
    reserve(initialElements.length);

    for (Point3d element : initialElements) {
      add(element);
    }
  }

  public Point3dList(Iterable<Point3d> initialElements) {
    this();
    for (Point3d element : initialElements) {
      add(element);
    }
  }

  public Point3d get(int index) {
    return doGet(index);
  }

  public Point3d set(int index, Point3d e) {
    return doSet(index, e);
  }

  public boolean add(Point3d e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Point3d e) {
    modCount++;
    doAdd(index, e);
  }

  public Point3d remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public Point3dList() {
    this(GestureEstimateJNI.new_Point3dList__SWIG_0(), true);
  }

  public Point3dList(Point3dList other) {
    this(GestureEstimateJNI.new_Point3dList__SWIG_1(Point3dList.getCPtr(other), other), true);
  }

  public long capacity() {
    return GestureEstimateJNI.Point3dList_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    GestureEstimateJNI.Point3dList_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return GestureEstimateJNI.Point3dList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    GestureEstimateJNI.Point3dList_clear(swigCPtr, this);
  }

  public Point3dList(int count, Point3d value) {
    this(GestureEstimateJNI.new_Point3dList__SWIG_2(count, Point3d.getCPtr(value), value), true);
  }

  private int doSize() {
    return GestureEstimateJNI.Point3dList_doSize(swigCPtr, this);
  }

  private void doAdd(Point3d x) {
    GestureEstimateJNI.Point3dList_doAdd__SWIG_0(swigCPtr, this, Point3d.getCPtr(x), x);
  }

  private void doAdd(int index, Point3d x) {
    GestureEstimateJNI.Point3dList_doAdd__SWIG_1(swigCPtr, this, index, Point3d.getCPtr(x), x);
  }

  private Point3d doRemove(int index) {
    return new Point3d(GestureEstimateJNI.Point3dList_doRemove(swigCPtr, this, index), true);
  }

  private Point3d doGet(int index) {
    return new Point3d(GestureEstimateJNI.Point3dList_doGet(swigCPtr, this, index), false);
  }

  private Point3d doSet(int index, Point3d val) {
    return new Point3d(GestureEstimateJNI.Point3dList_doSet(swigCPtr, this, index, Point3d.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    GestureEstimateJNI.Point3dList_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
