/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public class RightCutdownward extends Cutdownward {
  private transient long swigCPtr;

  protected RightCutdownward(long cPtr, boolean cMemoryOwn) {
    super(GestureEstimateJNI.RightCutdownward_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RightCutdownward obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GestureEstimateJNI.delete_RightCutdownward(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public boolean Detect(Point3fList body) {
    return GestureEstimateJNI.RightCutdownward_Detect(swigCPtr, this, Point3fList.getCPtr(body), body);
  }

  public RightCutdownward() {
    this(GestureEstimateJNI.new_RightCutdownward(), true);
  }

}
