/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public class TopLeftKnee {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TopLeftKnee(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TopLeftKnee obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GestureEstimateJNI.delete_TopLeftKnee(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean Detect(Point3fList body) {
    return GestureEstimateJNI.TopLeftKnee_Detect(swigCPtr, this, Point3fList.getCPtr(body), body);
  }

  public TopLeftKnee() {
    this(GestureEstimateJNI.new_TopLeftKnee(), true);
  }

}
