/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public class TwoIndexFingerRect extends Detector {
  private transient long swigCPtr;

  protected TwoIndexFingerRect(long cPtr, boolean cMemoryOwn) {
    super(GestureEstimateJNI.TwoIndexFingerRect_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TwoIndexFingerRect obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GestureEstimateJNI.delete_TwoIndexFingerRect(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public OptionalRect On(Point3fList left, Point3fList right) {
    return new OptionalRect(GestureEstimateJNI.TwoIndexFingerRect_On(swigCPtr, this, Point3fList.getCPtr(left), left, Point3fList.getCPtr(right), right), true);
  }

  public TwoIndexFingerRect() {
    this(GestureEstimateJNI.new_TwoIndexFingerRect(), true);
  }

}
