/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public class ZwnRect {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ZwnRect(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ZwnRect obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GestureEstimateJNI.delete_ZwnRect(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX(int value) {
    GestureEstimateJNI.ZwnRect_x_set(swigCPtr, this, value);
  }

  public int getX() {
    return GestureEstimateJNI.ZwnRect_x_get(swigCPtr, this);
  }

  public void setY(int value) {
    GestureEstimateJNI.ZwnRect_y_set(swigCPtr, this, value);
  }

  public int getY() {
    return GestureEstimateJNI.ZwnRect_y_get(swigCPtr, this);
  }

  public void setWidth(int value) {
    GestureEstimateJNI.ZwnRect_width_set(swigCPtr, this, value);
  }

  public int getWidth() {
    return GestureEstimateJNI.ZwnRect_width_get(swigCPtr, this);
  }

  public void setHeight(int value) {
    GestureEstimateJNI.ZwnRect_height_set(swigCPtr, this, value);
  }

  public int getHeight() {
    return GestureEstimateJNI.ZwnRect_height_get(swigCPtr, this);
  }

  public boolean empty() {
    return GestureEstimateJNI.ZwnRect_empty(swigCPtr, this);
  }

  public ZwnRect() {
    this(GestureEstimateJNI.new_ZwnRect(), true);
  }

}
