/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public class ArmDownDetector extends Detector {
  private transient long swigCPtr;

  protected ArmDownDetector(long cPtr, boolean cMemoryOwn) {
    super(GestureEstimateJNI.ArmDownDetector_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ArmDownDetector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GestureEstimateJNI.delete_ArmDownDetector(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ArmDownDetector() {
    this(GestureEstimateJNI.new_ArmDownDetector__SWIG_0(), true);
  }

  public ArmDownDetector(MotionCallback callback) {
    this(GestureEstimateJNI.new_ArmDownDetector__SWIG_1(MotionCallback.getCPtr(callback), callback), true);
  }

  public OptionalVec2f OnRight(Point3fList body) {
    return new OptionalVec2f(GestureEstimateJNI.ArmDownDetector_OnRight(swigCPtr, this, Point3fList.getCPtr(body), body), true);
  }

  public OptionalVec2f OnLeft(Point3fList body) {
    return new OptionalVec2f(GestureEstimateJNI.ArmDownDetector_OnLeft(swigCPtr, this, Point3fList.getCPtr(body), body), true);
  }

}
