/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public class ElbowToLeft {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ElbowToLeft(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ElbowToLeft obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GestureEstimateJNI.delete_ElbowToLeft(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean Detect(Point3fList body) {
    return GestureEstimateJNI.ElbowToLeft_Detect(swigCPtr, this, Point3fList.getCPtr(body), body);
  }

  public void setForearms_shoulder_angle(float value) {
    GestureEstimateJNI.ElbowToLeft_forearms_shoulder_angle_set(swigCPtr, this, value);
  }

  public float getForearms_shoulder_angle() {
    return GestureEstimateJNI.ElbowToLeft_forearms_shoulder_angle_get(swigCPtr, this);
  }

  public ElbowToLeft() {
    this(GestureEstimateJNI.new_ElbowToLeft(), true);
  }

}
