/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public class LeftCutdownward extends Cutdownward {
  private transient long swigCPtr;

  protected LeftCutdownward(long cPtr, boolean cMemoryOwn) {
    super(GestureEstimateJNI.LeftCutdownward_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LeftCutdownward obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GestureEstimateJNI.delete_LeftCutdownward(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public boolean Detect(Point3fList body) {
    return GestureEstimateJNI.LeftCutdownward_Detect(swigCPtr, this, Point3fList.getCPtr(body), body);
  }

  public LeftCutdownward() {
    this(GestureEstimateJNI.new_LeftCutdownward(), true);
  }

}
