/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public class OptionalFloat {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OptionalFloat(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OptionalFloat obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GestureEstimateJNI.delete_OptionalFloat(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public OptionalFloat() {
    this(GestureEstimateJNI.new_OptionalFloat__SWIG_0(), true);
  }

  public OptionalFloat(float value) {
    this(GestureEstimateJNI.new_OptionalFloat__SWIG_1(value), true);
  }

  public OptionalFloat(OptionalFloat other) {
    this(GestureEstimateJNI.new_OptionalFloat__SWIG_2(OptionalFloat.getCPtr(other), other), true);
  }

  public OptionalFloat assign(float value) {
    return new OptionalFloat(GestureEstimateJNI.OptionalFloat_assign__SWIG_0(swigCPtr, this, value), false);
  }

  public OptionalFloat assign(OptionalFloat other) {
    return new OptionalFloat(GestureEstimateJNI.OptionalFloat_assign__SWIG_1(swigCPtr, this, OptionalFloat.getCPtr(other), other), false);
  }

  public void swap(OptionalFloat other) {
    GestureEstimateJNI.OptionalFloat_swap(swigCPtr, this, OptionalFloat.getCPtr(other), other);
  }

  public float value() {
    return GestureEstimateJNI.OptionalFloat_value(swigCPtr, this);
  }

  public float value_or(float deflt) {
    return GestureEstimateJNI.OptionalFloat_value_or(swigCPtr, this, deflt);
  }

  public boolean is_specified() {
    return GestureEstimateJNI.OptionalFloat_is_specified(swigCPtr, this);
  }

  public void clear() {
    GestureEstimateJNI.OptionalFloat_clear(swigCPtr, this);
  }

}
