/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public class PunchingDector extends Detector {
  private transient long swigCPtr;

  protected PunchingDector(long cPtr, boolean cMemoryOwn) {
    super(GestureEstimateJNI.PunchingDector_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PunchingDector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GestureEstimateJNI.delete_PunchingDector(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public boolean OnLeft(Point3fList body, Point3fList left) {
    return GestureEstimateJNI.PunchingDector_OnLeft(swigCPtr, this, Point3fList.getCPtr(body), body, Point3fList.getCPtr(left), left);
  }

  public boolean OnRight(Point3fList body, Point3fList right) {
    return GestureEstimateJNI.PunchingDector_OnRight(swigCPtr, this, Point3fList.getCPtr(body), body, Point3fList.getCPtr(right), right);
  }

  public PunchingDector() {
    this(GestureEstimateJNI.new_PunchingDector(), true);
  }

}
