/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public class QuietDetector extends Detector {
  private transient long swigCPtr;

  protected QuietDetector(long cPtr, boolean cMemoryOwn) {
    super(GestureEstimateJNI.QuietDetector_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(QuietDetector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GestureEstimateJNI.delete_QuietDetector(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Hand On(Point3fList body, Point3fList left, Point3fList right) {
    return Hand.swigToEnum(GestureEstimateJNI.QuietDetector_On(swigCPtr, this, Point3fList.getCPtr(body), body, Point3fList.getCPtr(left), left, Point3fList.getCPtr(right), right));
  }

  public QuietDetector() {
    this(GestureEstimateJNI.new_QuietDetector(), true);
  }

}
