/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public class TranslateFistDetector extends Detector {
  private transient long swigCPtr;

  protected TranslateFistDetector(long cPtr, boolean cMemoryOwn) {
    super(GestureEstimateJNI.TranslateFistDetector_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TranslateFistDetector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GestureEstimateJNI.delete_TranslateFistDetector(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public boolean OnTranslateLeftFist(Point3fList left) {
    return GestureEstimateJNI.TranslateFistDetector_OnTranslateLeftFist(swigCPtr, this, Point3fList.getCPtr(left), left);
  }

  public boolean OnTranslateRightFist(Point3fList right) {
    return GestureEstimateJNI.TranslateFistDetector_OnTranslateRightFist(swigCPtr, this, Point3fList.getCPtr(right), right);
  }

  public TranslateFistDetector() {
    this(GestureEstimateJNI.new_TranslateFistDetector(), true);
  }

}
