/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public class ActionV2Detector extends Detector {
  private transient long swigCPtr;

  protected ActionV2Detector(long cPtr, boolean cMemoryOwn) {
    super(GestureEstimateJNI.ActionV2Detector_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ActionV2Detector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GestureEstimateJNI.delete_ActionV2Detector(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ActionV2Detector() {
    this(GestureEstimateJNI.new_ActionV2Detector__SWIG_0(), true);
  }

  public ActionV2Detector(MotionCallback cb) {
    this(GestureEstimateJNI.new_ActionV2Detector__SWIG_1(MotionCallback.getCPtr(cb), cb), true);
  }

  public ActionPoseV2Enum On(Point3fList body) {
    return ActionPoseV2Enum.swigToEnum(GestureEstimateJNI.ActionV2Detector_On(swigCPtr, this, Point3fList.getCPtr(body), body));
  }

  public void set_frame_len(int frame_len) {
    GestureEstimateJNI.ActionV2Detector_set_frame_len(swigCPtr, this, frame_len);
  }

  public void set_jump_shoulder_scale(float jump_shoulder_scale, float foot_chg) {
    GestureEstimateJNI.ActionV2Detector_set_jump_shoulder_scale(swigCPtr, this, jump_shoulder_scale, foot_chg);
  }

}
