/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public final class EyeStatusEnum {
  public final static EyeStatusEnum LeftEye = new EyeStatusEnum("LeftEye");
  public final static EyeStatusEnum RightEye = new EyeStatusEnum("RightEye");
  public final static EyeStatusEnum BothEye = new EyeStatusEnum("BothEye");
  public final static EyeStatusEnum NeitherEye = new EyeStatusEnum("NeitherEye");
  public final static EyeStatusEnum Unkonwn = new EyeStatusEnum("Unkonwn");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static EyeStatusEnum swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + EyeStatusEnum.class + " with value " + swigValue);
  }

  private EyeStatusEnum(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private EyeStatusEnum(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private EyeStatusEnum(String swigName, EyeStatusEnum swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static EyeStatusEnum[] swigValues = { LeftEye, RightEye, BothEye, NeitherEye, Unkonwn };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

