/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public class FlipPalmDetector extends Detector {
  private transient long swigCPtr;

  protected FlipPalmDetector(long cPtr, boolean cMemoryOwn) {
    super(GestureEstimateJNI.FlipPalmDetector_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FlipPalmDetector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GestureEstimateJNI.delete_FlipPalmDetector(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public boolean OnFlipLeftPalm(Point3fList left) {
    return GestureEstimateJNI.FlipPalmDetector_OnFlipLeftPalm(swigCPtr, this, Point3fList.getCPtr(left), left);
  }

  public boolean OnFlipRightPalm(Point3fList right) {
    return GestureEstimateJNI.FlipPalmDetector_OnFlipRightPalm(swigCPtr, this, Point3fList.getCPtr(right), right);
  }

  public FlipPalmDetector() {
    this(GestureEstimateJNI.new_FlipPalmDetector(), true);
  }

}
