/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public class LateralRaiseDetector extends Detector {
  private transient long swigCPtr;

  protected LateralRaiseDetector(long cPtr, boolean cMemoryOwn) {
    super(GestureEstimateJNI.LateralRaiseDetector_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LateralRaiseDetector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GestureEstimateJNI.delete_LateralRaiseDetector(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void setShoulder_straight_angle(float value) {
    GestureEstimateJNI.LateralRaiseDetector_shoulder_straight_angle_set(swigCPtr, this, value);
  }

  public float getShoulder_straight_angle() {
    return GestureEstimateJNI.LateralRaiseDetector_shoulder_straight_angle_get(swigCPtr, this);
  }

  public void setElbow_straight_angle(float value) {
    GestureEstimateJNI.LateralRaiseDetector_elbow_straight_angle_set(swigCPtr, this, value);
  }

  public float getElbow_straight_angle() {
    return GestureEstimateJNI.LateralRaiseDetector_elbow_straight_angle_get(swigCPtr, this);
  }

  public void setForearms_shoulder_angle(float value) {
    GestureEstimateJNI.LateralRaiseDetector_forearms_shoulder_angle_set(swigCPtr, this, value);
  }

  public float getForearms_shoulder_angle() {
    return GestureEstimateJNI.LateralRaiseDetector_forearms_shoulder_angle_get(swigCPtr, this);
  }

  public Hand On(Point3fList body) {
    return Hand.swigToEnum(GestureEstimateJNI.LateralRaiseDetector_On(swigCPtr, this, Point3fList.getCPtr(body), body));
  }

  public LateralRaiseDetector() {
    this(GestureEstimateJNI.new_LateralRaiseDetector(), true);
  }

}
