/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public class OptionalRect {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OptionalRect(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OptionalRect obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GestureEstimateJNI.delete_OptionalRect(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public OptionalRect() {
    this(GestureEstimateJNI.new_OptionalRect__SWIG_0(), true);
  }

  public OptionalRect(ZwnRect value) {
    this(GestureEstimateJNI.new_OptionalRect__SWIG_1(ZwnRect.getCPtr(value), value), true);
  }

  public OptionalRect(OptionalRect other) {
    this(GestureEstimateJNI.new_OptionalRect__SWIG_2(OptionalRect.getCPtr(other), other), true);
  }

  public OptionalRect assign(ZwnRect value) {
    return new OptionalRect(GestureEstimateJNI.OptionalRect_assign__SWIG_0(swigCPtr, this, ZwnRect.getCPtr(value), value), false);
  }

  public OptionalRect assign(OptionalRect other) {
    return new OptionalRect(GestureEstimateJNI.OptionalRect_assign__SWIG_1(swigCPtr, this, OptionalRect.getCPtr(other), other), false);
  }

  public void swap(OptionalRect other) {
    GestureEstimateJNI.OptionalRect_swap(swigCPtr, this, OptionalRect.getCPtr(other), other);
  }

  public ZwnRect value() {
    return new ZwnRect(GestureEstimateJNI.OptionalRect_value(swigCPtr, this), false);
  }

  public ZwnRect value_or(ZwnRect deflt) {
    return new ZwnRect(GestureEstimateJNI.OptionalRect_value_or(swigCPtr, this, ZwnRect.getCPtr(deflt), deflt), false);
  }

  public boolean is_specified() {
    return GestureEstimateJNI.OptionalRect_is_specified(swigCPtr, this);
  }

  public void clear() {
    GestureEstimateJNI.OptionalRect_clear(swigCPtr, this);
  }

}
