/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public class Point3i {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Point3i(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Point3i obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GestureEstimateJNI.delete_Point3i(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Point3i() {
    this(GestureEstimateJNI.new_Point3i__SWIG_0(), true);
  }

  public Point3i(int _x, int _y, int _z) {
    this(GestureEstimateJNI.new_Point3i__SWIG_1(_x, _y, _z), true);
  }

  public int dot(Point3i pt) {
    return GestureEstimateJNI.Point3i_dot(swigCPtr, this, Point3i.getCPtr(pt), pt);
  }

  public double ddot(Point3i pt) {
    return GestureEstimateJNI.Point3i_ddot(swigCPtr, this, Point3i.getCPtr(pt), pt);
  }

  public Point3i cross(Point3i pt) {
    return new Point3i(GestureEstimateJNI.Point3i_cross(swigCPtr, this, Point3i.getCPtr(pt), pt), true);
  }

  public void setX(int value) {
    GestureEstimateJNI.Point3i_x_set(swigCPtr, this, value);
  }

  public int getX() {
    return GestureEstimateJNI.Point3i_x_get(swigCPtr, this);
  }

  public void setY(int value) {
    GestureEstimateJNI.Point3i_y_set(swigCPtr, this, value);
  }

  public int getY() {
    return GestureEstimateJNI.Point3i_y_get(swigCPtr, this);
  }

  public void setZ(int value) {
    GestureEstimateJNI.Point3i_z_set(swigCPtr, this, value);
  }

  public int getZ() {
    return GestureEstimateJNI.Point3i_z_get(swigCPtr, this);
  }

}
