/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public class Point2fList extends java.util.AbstractList<Point2f> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Point2fList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Point2fList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GestureEstimateJNI.delete_Point2fList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Point2fList(Point2f[] initialElements) {
    this();
    reserve(initialElements.length);

    for (Point2f element : initialElements) {
      add(element);
    }
  }

  public Point2fList(Iterable<Point2f> initialElements) {
    this();
    for (Point2f element : initialElements) {
      add(element);
    }
  }

  public Point2f get(int index) {
    return doGet(index);
  }

  public Point2f set(int index, Point2f e) {
    return doSet(index, e);
  }

  public boolean add(Point2f e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Point2f e) {
    modCount++;
    doAdd(index, e);
  }

  public Point2f remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public Point2fList() {
    this(GestureEstimateJNI.new_Point2fList__SWIG_0(), true);
  }

  public Point2fList(Point2fList other) {
    this(GestureEstimateJNI.new_Point2fList__SWIG_1(Point2fList.getCPtr(other), other), true);
  }

  public long capacity() {
    return GestureEstimateJNI.Point2fList_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    GestureEstimateJNI.Point2fList_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return GestureEstimateJNI.Point2fList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    GestureEstimateJNI.Point2fList_clear(swigCPtr, this);
  }

  public Point2fList(int count, Point2f value) {
    this(GestureEstimateJNI.new_Point2fList__SWIG_2(count, Point2f.getCPtr(value), value), true);
  }

  private int doSize() {
    return GestureEstimateJNI.Point2fList_doSize(swigCPtr, this);
  }

  private void doAdd(Point2f x) {
    GestureEstimateJNI.Point2fList_doAdd__SWIG_0(swigCPtr, this, Point2f.getCPtr(x), x);
  }

  private void doAdd(int index, Point2f x) {
    GestureEstimateJNI.Point2fList_doAdd__SWIG_1(swigCPtr, this, index, Point2f.getCPtr(x), x);
  }

  private Point2f doRemove(int index) {
    return new Point2f(GestureEstimateJNI.Point2fList_doRemove(swigCPtr, this, index), true);
  }

  private Point2f doGet(int index) {
    return new Point2f(GestureEstimateJNI.Point2fList_doGet(swigCPtr, this, index), false);
  }

  private Point2f doSet(int index, Point2f val) {
    return new Point2f(GestureEstimateJNI.Point2fList_doSet(swigCPtr, this, index, Point2f.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    GestureEstimateJNI.Point2fList_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
