/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public class Point2d {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Point2d(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Point2d obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GestureEstimateJNI.delete_Point2d(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Point2d() {
    this(GestureEstimateJNI.new_Point2d__SWIG_0(), true);
  }

  public Point2d(double _x, double _y) {
    this(GestureEstimateJNI.new_Point2d__SWIG_1(_x, _y), true);
  }

  public double dot(Point2d pt) {
    return GestureEstimateJNI.Point2d_dot(swigCPtr, this, Point2d.getCPtr(pt), pt);
  }

  public double ddot(Point2d pt) {
    return GestureEstimateJNI.Point2d_ddot(swigCPtr, this, Point2d.getCPtr(pt), pt);
  }

  public double cross(Point2d pt) {
    return GestureEstimateJNI.Point2d_cross(swigCPtr, this, Point2d.getCPtr(pt), pt);
  }

  public void setX(double value) {
    GestureEstimateJNI.Point2d_x_set(swigCPtr, this, value);
  }

  public double getX() {
    return GestureEstimateJNI.Point2d_x_get(swigCPtr, this);
  }

  public void setY(double value) {
    GestureEstimateJNI.Point2d_y_set(swigCPtr, this, value);
  }

  public double getY() {
    return GestureEstimateJNI.Point2d_y_get(swigCPtr, this);
  }

}
