/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public class Point3iList extends java.util.AbstractList<Point3i> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Point3iList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Point3iList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GestureEstimateJNI.delete_Point3iList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Point3iList(Point3i[] initialElements) {
    this();
    reserve(initialElements.length);

    for (Point3i element : initialElements) {
      add(element);
    }
  }

  public Point3iList(Iterable<Point3i> initialElements) {
    this();
    for (Point3i element : initialElements) {
      add(element);
    }
  }

  public Point3i get(int index) {
    return doGet(index);
  }

  public Point3i set(int index, Point3i e) {
    return doSet(index, e);
  }

  public boolean add(Point3i e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Point3i e) {
    modCount++;
    doAdd(index, e);
  }

  public Point3i remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public Point3iList() {
    this(GestureEstimateJNI.new_Point3iList__SWIG_0(), true);
  }

  public Point3iList(Point3iList other) {
    this(GestureEstimateJNI.new_Point3iList__SWIG_1(Point3iList.getCPtr(other), other), true);
  }

  public long capacity() {
    return GestureEstimateJNI.Point3iList_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    GestureEstimateJNI.Point3iList_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return GestureEstimateJNI.Point3iList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    GestureEstimateJNI.Point3iList_clear(swigCPtr, this);
  }

  public Point3iList(int count, Point3i value) {
    this(GestureEstimateJNI.new_Point3iList__SWIG_2(count, Point3i.getCPtr(value), value), true);
  }

  private int doSize() {
    return GestureEstimateJNI.Point3iList_doSize(swigCPtr, this);
  }

  private void doAdd(Point3i x) {
    GestureEstimateJNI.Point3iList_doAdd__SWIG_0(swigCPtr, this, Point3i.getCPtr(x), x);
  }

  private void doAdd(int index, Point3i x) {
    GestureEstimateJNI.Point3iList_doAdd__SWIG_1(swigCPtr, this, index, Point3i.getCPtr(x), x);
  }

  private Point3i doRemove(int index) {
    return new Point3i(GestureEstimateJNI.Point3iList_doRemove(swigCPtr, this, index), true);
  }

  private Point3i doGet(int index) {
    return new Point3i(GestureEstimateJNI.Point3iList_doGet(swigCPtr, this, index), false);
  }

  private Point3i doSet(int index, Point3i val) {
    return new Point3i(GestureEstimateJNI.Point3iList_doSet(swigCPtr, this, index, Point3i.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    GestureEstimateJNI.Point3iList_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
