/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public final class PushPullType {
  public final static PushPullType Unkonwn = new PushPullType("Unkonwn");
  public final static PushPullType Push = new PushPullType("Push");
  public final static PushPullType Pull = new PushPullType("Pull");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static PushPullType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + PushPullType.class + " with value " + swigValue);
  }

  private PushPullType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private PushPullType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private PushPullType(String swigName, PushPullType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static PushPullType[] swigValues = { Unkonwn, Push, Pull };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

