/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public class PushPullDetector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PushPullDetector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PushPullDetector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GestureEstimateJNI.delete_PushPullDetector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PushPullDetector() {
    this(GestureEstimateJNI.new_PushPullDetector(), true);
  }

  public void SetPushPullDetector(int frame_count, float min_valid_height_thres, float horizontal_wrist_shoulder_thres, float vertical_wrist_shoulder_thres, int checkPoseCount, float push_pull_angle) {
    GestureEstimateJNI.PushPullDetector_SetPushPullDetector(swigCPtr, this, frame_count, min_valid_height_thres, horizontal_wrist_shoulder_thres, vertical_wrist_shoulder_thres, checkPoseCount, push_pull_angle);
  }

  public void InputInfoParam(Point3fList pose, Point3fList left, Point3fList right, Point3fList kpts3d) {
    GestureEstimateJNI.PushPullDetector_InputInfoParam(swigCPtr, this, Point3fList.getCPtr(pose), pose, Point3fList.getCPtr(left), left, Point3fList.getCPtr(right), right, Point3fList.getCPtr(kpts3d), kpts3d);
  }

  public PushPullType GetLeftPushPullStatus() {
    return PushPullType.swigToEnum(GestureEstimateJNI.PushPullDetector_GetLeftPushPullStatus(swigCPtr, this));
  }

  public PushPullType GetRightPushPullStatus() {
    return PushPullType.swigToEnum(GestureEstimateJNI.PushPullDetector_GetRightPushPullStatus(swigCPtr, this));
  }

  public float GetCurLeftArmAngle() {
    return GestureEstimateJNI.PushPullDetector_GetCurLeftArmAngle(swigCPtr, this);
  }

  public float GetCurRightArmAngle() {
    return GestureEstimateJNI.PushPullDetector_GetCurRightArmAngle(swigCPtr, this);
  }

}
