/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public class SlipV2Detector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SlipV2Detector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SlipV2Detector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GestureEstimateJNI.delete_SlipV2Detector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SlipV2Detector() {
    this(GestureEstimateJNI.new_SlipV2Detector(), true);
  }

  public FloatList OnLeftHandAngle(Point3fList hand_kpt) {
    return new FloatList(GestureEstimateJNI.SlipV2Detector_OnLeftHandAngle(swigCPtr, this, Point3fList.getCPtr(hand_kpt), hand_kpt), true);
  }

  public SlipEnum OnLeftHand(Point3fList left, Point3fList pose) {
    return SlipEnum.swigToEnum(GestureEstimateJNI.SlipV2Detector_OnLeftHand(swigCPtr, this, Point3fList.getCPtr(left), left, Point3fList.getCPtr(pose), pose));
  }

  public SlipEnum OnRightHand(Point3fList right, Point3fList pose) {
    return SlipEnum.swigToEnum(GestureEstimateJNI.SlipV2Detector_OnRightHand(swigCPtr, this, Point3fList.getCPtr(right), right, Point3fList.getCPtr(pose), pose));
  }

  public void SetSlipV2CheckBodyMoveThres(float body_horizontal_move_thres, float body_vertical_move_thres) {
    GestureEstimateJNI.SlipV2Detector_SetSlipV2CheckBodyMoveThres(swigCPtr, this, body_horizontal_move_thres, body_vertical_move_thres);
  }

  public void SetSlipV2MoveThres(float hand_horizontal_move_thres, float hand_vertical_move_thres, float hand_horizontal_move_slope_angle, float hand_vertical_move_slope_angle, int frame_count, boolean dis_body_move) {
    GestureEstimateJNI.SlipV2Detector_SetSlipV2MoveThres(swigCPtr, this, hand_horizontal_move_thres, hand_vertical_move_thres, hand_horizontal_move_slope_angle, hand_vertical_move_slope_angle, frame_count, dis_body_move);
  }

}
