/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public class StaticHandPoseV2Detector extends Detector {
  private transient long swigCPtr;

  protected StaticHandPoseV2Detector(long cPtr, boolean cMemoryOwn) {
    super(GestureEstimateJNI.StaticHandPoseV2Detector_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StaticHandPoseV2Detector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GestureEstimateJNI.delete_StaticHandPoseV2Detector(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public HandPoseEnum Detect(Point3fList hand_kpt) {
    return HandPoseEnum.swigToEnum(GestureEstimateJNI.StaticHandPoseV2Detector_Detect(swigCPtr, this, Point3fList.getCPtr(hand_kpt), hand_kpt));
  }

  public boolean CheckPoseDirection(Point3fList kpts, HandPoseEnum Handpose) {
    return GestureEstimateJNI.StaticHandPoseV2Detector_CheckPoseDirection(swigCPtr, this, Point3fList.getCPtr(kpts), kpts, Handpose.swigValue());
  }

  public void SetPoseUpWardAngle(float min_angle, float max_angle) {
    GestureEstimateJNI.StaticHandPoseV2Detector_SetPoseUpWardAngle(swigCPtr, this, min_angle, max_angle);
  }

  public StaticHandPoseV2Detector() {
    this(GestureEstimateJNI.new_StaticHandPoseV2Detector(), true);
  }

}
