/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public final class ZwnFaceAlignType {
  public final static ZwnFaceAlignType FACE_ALIGN_UNKNOWN = new ZwnFaceAlignType("FACE_ALIGN_UNKNOWN", GestureEstimateJNI.ZwnFaceAlignType_FACE_ALIGN_UNKNOWN_get());
  public final static ZwnFaceAlignType FACE_ALIGN = new ZwnFaceAlignType("FACE_ALIGN");
  public final static ZwnFaceAlignType FACE_ALIGN_UP = new ZwnFaceAlignType("FACE_ALIGN_UP");
  public final static ZwnFaceAlignType FACE_ALIGN_DOWN = new ZwnFaceAlignType("FACE_ALIGN_DOWN");
  public final static ZwnFaceAlignType FACE_ALIGN_LEFT = new ZwnFaceAlignType("FACE_ALIGN_LEFT");
  public final static ZwnFaceAlignType FACE_ALIGN_RIGHT = new ZwnFaceAlignType("FACE_ALIGN_RIGHT");
  public final static ZwnFaceAlignType FACE_ALIGN_UPLEFT = new ZwnFaceAlignType("FACE_ALIGN_UPLEFT");
  public final static ZwnFaceAlignType FACE_ALIGN_UPRIGHT = new ZwnFaceAlignType("FACE_ALIGN_UPRIGHT");
  public final static ZwnFaceAlignType FACE_ALIGN_DOWNLEFT = new ZwnFaceAlignType("FACE_ALIGN_DOWNLEFT");
  public final static ZwnFaceAlignType FACE_ALIGN_DOWNRIGHT = new ZwnFaceAlignType("FACE_ALIGN_DOWNRIGHT");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ZwnFaceAlignType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ZwnFaceAlignType.class + " with value " + swigValue);
  }

  private ZwnFaceAlignType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ZwnFaceAlignType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ZwnFaceAlignType(String swigName, ZwnFaceAlignType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ZwnFaceAlignType[] swigValues = { FACE_ALIGN_UNKNOWN, FACE_ALIGN, FACE_ALIGN_UP, FACE_ALIGN_DOWN, FACE_ALIGN_LEFT, FACE_ALIGN_RIGHT, FACE_ALIGN_UPLEFT, FACE_ALIGN_UPRIGHT, FACE_ALIGN_DOWNLEFT, FACE_ALIGN_DOWNRIGHT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

