/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public class ZwnVerticalWaveConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ZwnVerticalWaveConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ZwnVerticalWaveConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GestureEstimateJNI.delete_ZwnVerticalWaveConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMove_vertical_thres(float value) {
    GestureEstimateJNI.ZwnVerticalWaveConfig_move_vertical_thres_set(swigCPtr, this, value);
  }

  public float getMove_vertical_thres() {
    return GestureEstimateJNI.ZwnVerticalWaveConfig_move_vertical_thres_get(swigCPtr, this);
  }

  public void setMove_horizontal_slope_thres(float value) {
    GestureEstimateJNI.ZwnVerticalWaveConfig_move_horizontal_slope_thres_set(swigCPtr, this, value);
  }

  public float getMove_horizontal_slope_thres() {
    return GestureEstimateJNI.ZwnVerticalWaveConfig_move_horizontal_slope_thres_get(swigCPtr, this);
  }

  public void setUp_recognition_wrist_shoulder_thres(float value) {
    GestureEstimateJNI.ZwnVerticalWaveConfig_up_recognition_wrist_shoulder_thres_set(swigCPtr, this, value);
  }

  public float getUp_recognition_wrist_shoulder_thres() {
    return GestureEstimateJNI.ZwnVerticalWaveConfig_up_recognition_wrist_shoulder_thres_get(swigCPtr, this);
  }

  public void setDown_recognition_wrist_shoulder_thres(float value) {
    GestureEstimateJNI.ZwnVerticalWaveConfig_down_recognition_wrist_shoulder_thres_set(swigCPtr, this, value);
  }

  public float getDown_recognition_wrist_shoulder_thres() {
    return GestureEstimateJNI.ZwnVerticalWaveConfig_down_recognition_wrist_shoulder_thres_get(swigCPtr, this);
  }

  public void setUp_down_need_move_pass(boolean value) {
    GestureEstimateJNI.ZwnVerticalWaveConfig_up_down_need_move_pass_set(swigCPtr, this, value);
  }

  public boolean getUp_down_need_move_pass() {
    return GestureEstimateJNI.ZwnVerticalWaveConfig_up_down_need_move_pass_get(swigCPtr, this);
  }

  public void setUp_down_no_move_delay_count(int value) {
    GestureEstimateJNI.ZwnVerticalWaveConfig_up_down_no_move_delay_count_set(swigCPtr, this, value);
  }

  public int getUp_down_no_move_delay_count() {
    return GestureEstimateJNI.ZwnVerticalWaveConfig_up_down_no_move_delay_count_get(swigCPtr, this);
  }

  public void setUp_down_action_no_move_thres(float value) {
    GestureEstimateJNI.ZwnVerticalWaveConfig_up_down_action_no_move_thres_set(swigCPtr, this, value);
  }

  public float getUp_down_action_no_move_thres() {
    return GestureEstimateJNI.ZwnVerticalWaveConfig_up_down_action_no_move_thres_get(swigCPtr, this);
  }

  public ZwnVerticalWaveConfig() {
    this(GestureEstimateJNI.new_ZwnVerticalWaveConfig(), true);
  }

}
