/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.GestureEstimate;

public class ZwnWaveCommonConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ZwnWaveCommonConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ZwnWaveCommonConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GestureEstimateJNI.delete_ZwnWaveCommonConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMove_min_valid_height_thres(float value) {
    GestureEstimateJNI.ZwnWaveCommonConfig_move_min_valid_height_thres_set(swigCPtr, this, value);
  }

  public float getMove_min_valid_height_thres() {
    return GestureEstimateJNI.ZwnWaveCommonConfig_move_min_valid_height_thres_get(swigCPtr, this);
  }

  public void setCheck_interval_time(float value) {
    GestureEstimateJNI.ZwnWaveCommonConfig_check_interval_time_set(swigCPtr, this, value);
  }

  public float getCheck_interval_time() {
    return GestureEstimateJNI.ZwnWaveCommonConfig_check_interval_time_get(swigCPtr, this);
  }

  public void setFrame_count(int value) {
    GestureEstimateJNI.ZwnWaveCommonConfig_frame_count_set(swigCPtr, this, value);
  }

  public int getFrame_count() {
    return GestureEstimateJNI.ZwnWaveCommonConfig_frame_count_get(swigCPtr, this);
  }

  public ZwnWaveCommonConfig() {
    this(GestureEstimateJNI.new_ZwnWaveCommonConfig(), true);
  }

}
